name: nightlies

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      skip_build:
        description: 'skip'
        required: false
        type: boolean
        default: false

concurrency:
  group: nightly
  cancel-in-progress: true

jobs:
  build:
    runs-on: docker
    container:
      image: eclipse-temurin:21-jdk

    if: ${{ !(forgejo.event_name == 'workflow_dispatch' && inputs.skip_build == true) }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: gradle caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-

      - name: gradlew
        run: chmod +x ./gradlew

      - name: build
        env:
          SIGNING_KEYSTORE_B64: ${{ secrets.SIGNING_KEYSTORE_B64 }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: ./gradlew clean assembleRelease

      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightly-release-apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7
